# Secrets Manager (for holding sensitive data) - Options are: vault, ssm or none
secrets_manager:
  value: none

# Image Repository - Options: ecr, docker, quay, gcr
image_repository:
  value: ecr
  
# Specify Kubernetes version: Options: Kubernetes 1.11, 1.12, 1.13, and 1.14
kubectl:
  version: 1.13.7

# Options are: prod, qa
environment:
  default: qa

# Options are: AWS and GCP
cloud_platform:
  gcp:
    name: gcp
    enabled: true
    project_id: zinbabel
    region: us-east-2
    credentials: some-gcp-role
  aws:
    name: aws
    enabled: false
    region: us-east-2
  az:
    name: az
    enabled: false
    region: us-east-2

# Options are: Travis, Gitlab, Jenkins
ci_platform:
  - travis:
    name: travis
    enabled: false
  - gitlab:
    name: gitlab
    enabled: true
  - jenkins:
    name: jenkins
    enabled: false

# Specify Terraform version. Options: Terraform 0.11.14 or 0.12.21
terraform:
  actions:
    - terraform_plan:
      name: terraform_plan
      enabled: false
    - terraform_apply: 
      name: terraform_apply
      enabled: false
    - terraform_destroy:
      name: terraform_destroy
      enabled: false

# Specify Helm version. Options: 2 or 3
helm:
  namespace: default
  actions: 
    - deploy_charts:
      name: deploy_charts
      enabled: true
    - external_helm_charts:
      name: external_helm_charts
      enabled: false
      chart_name: <CHART_NAME>
      url: <URL>
    - helm_s3_repo:
      name: helm_s3_repo
      enabled: false
      chart_name: <CHART_NAME>
      url: <URL>      
    - override_default:
      name: override_default
      enabled: false
      helm_directory: <DIRECTORY_NAME>

ansible:
  actions:
    - deploy_playbooks: 
      name: deploy_playbooks
      enabled: false
    - override_default:
      name: override_default
      enabled: false
      ansible_directory: <DIRECTORY_NAME>
