bitops:
  type: object
  properties:

    project:
      type: object
      properties:
        source:
          type: string
    
    environment:
      type: string

    logging:
      type: object
      properties:
        level:
          type: string
        file:
          type: string
        err:
          type: string
        rotation:
          type: int

    plugins:
      type: object
      properties:
        plugin:
          type: object
          properties:
            source: 
              type: string
            version:
              type: string
            logging:
              type: object
              properties:
                level:
                  type: string
                file:
                  type: string
                err:
                  type: string
                rotation:
                  type: int
