helm:
  cli:
    backend-config:
      - KEY1=value
      - KEY2=value
      - KEY3=value
      - KEY4=value
      - KEY5=value
      - KEY6=value
    namespace: bitops
    debug: false
    atomic: true
  options:
      release-name: bitops-eks
      kubeconfig:
        fetch:
          enabled: true
          cluster-name: bitops-eks